/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(3,"Social Links Menu","social-links-menu",0),
(4,"post-format-link","post-format-link",0),
(5,"post-format-image","post-format-image",0),
(6,"post-format-quote","post-format-quote",0),
(7,"post-format-video","post-format-video",0),
(8,"post-format-audio","post-format-audio",0),
(9,"post-format-gallery","post-format-gallery",0),
(10,"new","new",0),
(11,"something","something",0),
(12,"Business","business",0),
(13,"Market","market",0),
(14,"special","special",0),
(15,"Main menu","main-menu",0),
(16,"One more","one-more",0),
(17,"Slim","slim",0),
(18,"Shop","shop",0),
(19,"No Posts","noposts",0),
(20,"Gole","gole",0),
(21,"Bang Bang","bang-bang",0),
(22,"Fine","fine",0),
(23,"Good","good",0),
(24,"Footer Left Menu","footer-left-menu",0),
(25,"Footer Middle Menu","footer-middle-menu",0),
(26,"Footer Right Menu","footer-right-menu",0),
(27,"English","english",0),
(28,"Bangla","bangla",0),
(29,"Friench","friench",0),
(30,"Classic","classic",0),
(31,"Thriller","thriller",0),
(32,"Horror","horror",0),
(33,"newterm","newterm",0),
(34,"newterm2","newterm2",0),
(35,"newterm3","newterm3",0),
(36,"Another Test Category","another-test-category",0),
(37,"Test Tag","test-tag",0),
(38,"Genre Test","genre-test",0),
(39,"Romantic","romantic",0),
(40,"Action","action",0),
(41,"Sci-fi","sci-fi",0);
